- .eslintrc
- .prettierrc
- package-lock.json
- package.json
```
cleancode를 위한 linter, formatter 추가 PR
```
```
1. eslint 추가
2. formatter 추가
```
- VSCode 에서 관련 Extention 설치해주세요!
> chore: linter, formatter 추가

- .gitignore
- about.html
- app.js
- assets/js/authorization/cookieutils.js
- assets/js/authorization/login.js
- assets/js/config.js
- assets/js/custom.js
- assets/js/gatherings.js
- assets/js/write-exhibition-form.js
- gathering-new.html
- gathering.html
- index.html
- login.html
- package-lock.json
- package.json
- pricing.html
- work-single.html
- work.html
- write-exhibition-form.html
feat: BASEURL 설정 및 Login 로직 수정
feat: BASEURL 설정 및 Login 로직 수정
x
> feat: BASEURL 설정 및 Login 로직 수정

- app.js
- assets/css/templatemo.css
- assets/js/custom.js
- exhibition-single.html
- exhibition.html
전시회 전체 조회 및 상세 조회 페이지 구현
- Index.html의 Work.html과 work-single.html을 exhibition.html & exihibition-single.html로 대체했다고 보시면 됩니다!
> feat: 전시회 전체 조회 및 상세조회 페이지 구현

- assets/js/custom.js
메인페이지 base_url 오타로 인한 fetch 오류 문제 수정
> Bug: BASE_URL 오타로 인한 fetch 오류 문제 수정

- .github/workflows/frontend.yml
CI 파이프라인 수정
fix: CI 파이프라인 수정 작업입니다!
X
> fix: CI 파이프라인 수정

- Dockerfile
간략히 어떤 기능에 대한 pull request인지 적어주세요.
> fix: 도커파일 수정

- assets/js/custom.js
- my-gatherings.html
마이페이지 수정
리뷰 페이지 방문 날짜 렌더링 안되는 오류 해결, 모집글 페이지 신청자 보기 연동
> Fix: 리뷰페이지 방문날짜, 모집글 페이지 신청자 보기 수정

- exhibition-single.html
리뷰 삭제 기능 구현, 전시 함께봐요 버튼 추가, credential 설정
> feat: 리뷰 삭제 기능 구현

- assets/js/config.js
- assets/js/gathering-render.js
- assets/js/write-exhibition-form.js
- gathering.html
- write-exhibition-form.html
전시 함께 가요 페이지를 리팩토링하였습니다.
Base Url이 빠져 있는 부분을 수정했습니다.
로그인하지 않은 상태에서 접근할 경우 로그인 Alert를 띄우고 로그인 페이지로 리다이렉트 하도록 했습니다.
누락된 필드 (detailInfoUrl) 입력 폼을 만들고 데이터를 받아 백엔드로 전송했습니다.
추후 배포 환경 테스트 진행할 예정입니다.
> 50 전시 함께 가요 페이지 리팩토링 1

- .github/workflows/frontend.yml
간략히 어떤 기능에 대한 pull request인지 적어주세요.
> fix: 파이프라인 수정

- assets/css/bootstrap.css
- exhibition-single.html
- exhibition.html
누락된 삭제 버튼 추가
전시회 상세 조회 리뷰란에 누락된 삭제 버튼 추가
> feat: 삭제 버튼 추가

- assets/js/custom.js
신청한 유저 승인하는 기능 추가했습니다
custom.js에 메서드 추가 했습니다
> feat: 신청 유저 승인 기능 추가

- assets/css/mypage.css
- assets/js/custom.js
- my-participations.html
마이페이지 - 참가 신청한 모집글을 승낙 여부에 따라 분리함
> 마이 참가모집글 승낙 대기 완료 분리

- assets/js/config.js
- assets/js/custom.js
> fix: 로그인 로그아웃 버튼 바뀌게 수정

- assets/js/config.js
간략히 어떤 기능에 대한 pull request인지 적어주세요.
> fix baseurl 수정

- app.js
- assets/css/login.css
- assets/js/authorization/join.js
- assets/js/authorization/login.js
- form-bootstrap.html
- join.html
- login.html
회원가입 페이지 구현했습니다.
기존에 재근님께서 join.html, join.js에 구현하셨던 내용을 모두 login.html, login.js에 합쳤습니다.
이제 join.html과 join.js는 제거해도 무관합니다
> 13 fe 회원가입 페이지 구현

- assets/css/custom.css
- exhibition-single.html
- gathering-new.html
전시 상세조회 페이지 -> 함께 전시가요 모집글 페이지로 이동 시, 전시 id와 전시 이름을 가져오는 작업입니다. 
- 전시 이름 불러오기
- 전시 id 폼 input에 꽂아주고 숨김처리
- 함께 전시가요 모집글 페이지 배경이미지 변경
전시 상세조회 페이지에서 함께 전시가요 모집글 페이지로 이동해서 새로운 글 작성 한 번만 부탁드립니다!
> 62 함께전시가요 모집글수정

- assets/js/config.js
- exhibition-single.html
- package-lock.json
전시회 상세 조회 관람객 통계 항목 추가
이미지 url이 없을 경우 공백으로 출력
-[ ] 전시회 상세 조회 관람객 통계 항목 추가
-[ ] 이미지 url이 없을 경우 공백으로 출력
> 79 전시회 상세 조회 항목 추가

- assets/js/config.js
- assets/js/write-exhibition-form.js
- write-exhibition-form.html
전시 등록 기능을 구현할 때 첨부한 이미지의 s3 이미지 주소가 db에 저장되도록 했습니다.
x
x
> 40 aws s3 연동 기능 추가 1

- assets/js/write-exhibition-form.js
간략히 어떤 기능에 대한 pull request인지 적어주세요.
> main -> develop

- assets/js/custom.js
> 로그인,로그아웃,버튼 수정

- assets/js/custom.js
- assets/js/write-exhibition-form.js
> fix: 로그인,로그아웃,버튼 수정

- assets/css/custom.css
- assets/js/config.js
- exhibition.html
전시 조회 페이지에서 전시 등록 버튼을 추가했습니다.
x
x
> Feat: 전시 등록하기 버튼 추가
